#:schema node_modules/wrangler/config-schema.json
name = "taiwanalert"
main = "src/index.ts"
compatibility_date = "2024-04-19"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[vars]
CHATID = -1002118573662

