[package]
name = "external"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = { version = "1.0.213", features = ["derive"] }
futures-io = { version = "0.2.0-beta" }
serde_json = "1.0.132"
chrono = "0.4.38"
pickledb = "0.5.1"
csv = "1.3.0"
scraper = "0.21.0"
regex = "1.11.1"
