[package]
name = "external"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = "1.0.213"
futures-io = { version = "0.2.0-beta" }